### ISSUE TITLE
command make problem

### ISSUE THREAD

**Issue by m8710200** [frederikhermans/openrq-cli#1]
when i follow the command

do make it say:

javac: directory not found: bin/src/se/uu/it/uno/openrqcli/Main.java
Usage: javac <options> <source files>
use -help for a list of possible options
make: **\* [all] Error 2

could somebody help me?

**Comment by frederikhermans** [comment]
That was a bug in the Makefile, which didn't create the bin/ directory. It is fixed now.

Thank you for reporting!

**Comment by m8710200** [comment]
Thanks!

2016-08-17 4:41 GMT+08:00 frederikhermans notifications@github.com:
