### ISSUE TITLE
decode succeeded but the file could not open!

### ISSUE THREAD

**Issue by m8710200** [frederikhermans/openrq-cli#2]
First, Thanks your help!

makefile is ok!

When I put the picture(i.e 123.jpg) into the encoder , it's generate a file(i.e 123.encoded, this file couldn't open.)

and I put 123.encoded into the decoder , it's succeeded! but the file 123.decoded.jpg couldn't open too!

**Comment by frederikhermans** [comment]
I cannot reproduce the problem.

Can you please send the exact commands (with parameters) you are using, the output you get, and the file that you're encoding?

**Comment by m8710200** [comment]
this is my command

openrq-cli encode 64 31 1000 < 1.jpg > 1.encoded

openrq-cli decode 64 31 51492 < 1.encoded > 1.decoded.jpg

thanks you!

2016-08-17 15:39 GMT+08:00 frederikhermans notifications@github.com:

**Comment by frederikhermans** [comment]
What's 1.jpg? Is its size 51492 bytes? Note that the third argument to `decode` must be the size of the file to be decoded. If the argument is wrong, the output will (most likely) be wrong.

Also make sure to create sufficiently many repair blocks. The number of repair blocks is specified as the third argument to the `encode` command.

**Comment by m8710200** [comment]
1.jpg just a picture , the third argument need to equal to the file size?

2016-08-17 15:54 GMT+08:00 frederikhermans notifications@github.com:

**Comment by frederikhermans** [comment]
Yes, the third argument to `decode` must equal the picture's file size.

**Comment by m8710200** [comment]
I try, but it still fail!

1.jpg file size 161.1kb

the third argument i set 20620 (bytes)

but it still fail open

2016-08-17 16:01 GMT+08:00 frederikhermans notifications@github.com:

**Comment by frederikhermans** [comment]
If the image size is 161.1 KB, why do you set the third argument to 20620?

Try this:

```
wget -O chess.png https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Chess_qlt45.svg/600px-Chess_qlt45.svg.png
openrq-cli encode 64 31 1000 < chess.png > chess.encoded
openrq-cli decode 64 31 28635 < chess.encoded > chess.decoded.png
```

Note that the third argument to `decode` is 28635, because chess.png is 28635 bytes in size.

Can you open chess.decoded.png after those steps?

**Comment by m8710200** [comment]
succeeded!! so my argument really wrong!

Thanks!! but why chess.encoded couldn't open?

2016-08-17 16:19 GMT+08:00 frederikhermans notifications@github.com:

**Comment by frederikhermans** [comment]
The encoded file cannot be opened directly, as it contains only repair blocks.

**Comment by m8710200** [comment]
ok! thank you ! I am so appreciation!

**Comment by m8710200** [comment]
Sorry, I still have confusing on encoded file.

If we wanted to decode the file,we should to get source symbol and repair
symbol.

So the encoded file shouldn't only have repair block right?

If it's true , why only have repair block can make decode finishing?

Thank you!

2016-08-17 17:26 GMT+08:00 frederikhermans notifications@github.com:

**Comment by frederikhermans** [comment]
Repair blocks by themselves are sufficient to decode the payload. This has to do with the design of Raptor codes.

I suggest you to read a bit more about how Raptor codes work and have a close look at the openrq implementation as well. Please not that I am not involved in the development of openrq and wrote the code in the openrq-cli repository only for some other project.
